### ISSUE TITLE
py3nvml dependency should be removed? (also unable to install on osx-arm64 because of it)

### ISSUE THREAD

**Issue by aldanor** [conda-forge/aim-feedstock#30]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Technically, osx-arm64 build of aim exists on conda-forge, however [py3nvml](https://github.com/conda-forge/py3nvml-feedstock) doesn't exist for osx-arm64, so aim cannot be installed.

Given that `py3nvml` doesn't even appear in aim's latest `setup.py` (since it has been removed as a dependency in https://github.com/aimhubio/aim/pull/2364), it looks like it should be removed from this feedstock as well? This should also make it installable on M1 once again.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by synapticarbors** [comment]
This should be fixed in the latest release I pushed.
